/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_cdemo_CallUtils */

#ifndef _Included_com_example_cdemo_CallUtils
#define _Included_com_example_cdemo_CallUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_cdemo_CallUtils
 * Method:    callSimpleInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_cdemo_CallUtils_callSimpleInfo
  (JNIEnv *env, jclass ojb) {
      return (*env) -> NewStringUTF(env,"Hello, I'm an info come from use ndk-build");
  };

#ifdef __cplusplus
}
#endif
#endif
